# Generated by Django 5.2.6 on 2025-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=120)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('availability', models.CharField(default='Available', max_length=20)),
                ('fee', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('reviews', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
